# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

from overload import CustomLineEdit,CustomListWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(745, 662)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(130, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_add.setFont(font)
        self.btn_add.setObjectName("btn_add")
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset.setGeometry(QtCore.QRect(250, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_reset.setFont(font)
        self.btn_reset.setObjectName("btn_reset")
        self.list_pend = CustomListWidget(self.centralwidget)
        self.list_pend.setGeometry(QtCore.QRect(10, 50, 111, 421))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.list_pend.setFont(font)
        self.list_pend.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.list_pend.setDragEnabled(True)
        self.list_pend.setDragDropOverwriteMode(False)
        self.list_pend.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.list_pend.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.list_pend.setObjectName("list_pend")
        self.list_push = CustomListWidget(self.centralwidget)
        self.list_push.setGeometry(QtCore.QRect(130, 50, 111, 421))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.list_push.setFont(font)
        self.list_push.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.list_push.setDragEnabled(True)
        self.list_push.setDragDropOverwriteMode(False)
        self.list_push.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.list_push.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.list_push.setObjectName("list_push")
        self.list_dept = CustomListWidget(self.centralwidget)
        self.list_dept.setGeometry(QtCore.QRect(250, 50, 111, 421))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.list_dept.setFont(font)
        self.list_dept.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.list_dept.setDragEnabled(True)
        self.list_dept.setDragDropOverwriteMode(False)
        self.list_dept.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.list_dept.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.list_dept.setObjectName("list_dept")
        self.lineEdit = CustomLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setMaxLength(10)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 745, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSet_opacity = QtWidgets.QAction(MainWindow)
        self.actionSet_opacity.setObjectName("actionSet_opacity")
        self.actionStay_on_top = QtWidgets.QAction(MainWindow)
        self.actionStay_on_top.setCheckable(True)
        self.actionStay_on_top.setObjectName("actionStay_on_top")
        self.actionFlights_handled = QtWidgets.QAction(MainWindow)
        self.actionFlights_handled.setObjectName("actionFlights_handled")
        self.actionFlights_departed = QtWidgets.QAction(MainWindow)
        self.actionFlights_departed.setObjectName("actionFlights_departed")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.actionFlight_handled = QtWidgets.QAction(MainWindow)
        self.actionFlight_handled.setObjectName("actionFlight_handled")
        self.actionFlights_departed_2 = QtWidgets.QAction(MainWindow)
        self.actionFlights_departed_2.setObjectName("actionFlights_departed_2")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuSettings.addAction(self.actionSet_opacity)
        self.menuSettings.addAction(self.actionStay_on_top)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionFlight_handled)
        self.menuSettings.addAction(self.actionFlights_departed_2)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionAbout)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionExit)
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.btn_add.clicked.connect(MainWindow.addFlight)
        self.btn_reset.clicked.connect(MainWindow.resetLists)
        self.lineEdit.returnPressed.connect(self.btn_add.click)
        self.list_push.itemDoubleClicked['QListWidgetItem*'].connect(MainWindow.setStatusClr)
        self.list_dept.itemDoubleClicked['QListWidgetItem*'].connect(MainWindow.setStatusDep)
        self.list_pend.itemDoubleClicked['QListWidgetItem*'].connect(MainWindow.setStatusClr)
        self.menuBar.triggered['QAction*'].connect(MainWindow.clickMenu)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.btn_add)
        MainWindow.setTabOrder(self.btn_add, self.list_pend)
        MainWindow.setTabOrder(self.list_pend, self.list_push)
        MainWindow.setTabOrder(self.list_push, self.list_dept)
        MainWindow.setTabOrder(self.list_dept, self.btn_reset)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Flight Strip Manager"))
        self.btn_add.setText(_translate("MainWindow", "ADD"))
        self.btn_reset.setText(_translate("MainWindow", "RESET"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Callsign"))
        self.menuSettings.setTitle(_translate("MainWindow", "Menu"))
        self.actionSet_opacity.setText(_translate("MainWindow", "Set opacity"))
        self.actionStay_on_top.setText(_translate("MainWindow", "Stay on top"))
        self.actionFlights_handled.setText(_translate("MainWindow", "Flights handled"))
        self.actionFlights_departed.setText(_translate("MainWindow", "Flights departed"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
        self.actionFlight_handled.setText(_translate("MainWindow", "Flights handled"))
        self.actionFlights_departed_2.setText(_translate("MainWindow", "Flights departed"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
