# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

from overload import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(744, 662)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(130, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_add.setFont(font)
        self.btn_add.setObjectName("btn_add")
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset.setGeometry(QtCore.QRect(250, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_reset.setFont(font)
        self.btn_reset.setObjectName("btn_reset")
        self.list_pend = CustomListWidget(self.centralwidget)
        self.list_pend.setGeometry(QtCore.QRect(10, 50, 111, 421))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.list_pend.setFont(font)
        self.list_pend.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.list_pend.setDragEnabled(True)
        self.list_pend.setDragDropOverwriteMode(False)
        self.list_pend.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.list_pend.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.list_pend.setObjectName("list_pend")
        self.list_push = CustomListWidget(self.centralwidget)
        self.list_push.setGeometry(QtCore.QRect(130, 50, 111, 421))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.list_push.setFont(font)
        self.list_push.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.list_push.setDragEnabled(True)
        self.list_push.setDragDropOverwriteMode(False)
        self.list_push.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.list_push.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.list_push.setObjectName("list_push")
        self.list_dept = CustomListWidget(self.centralwidget)
        self.list_dept.setGeometry(QtCore.QRect(250, 50, 111, 421))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.list_dept.setFont(font)
        self.list_dept.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.list_dept.setDragEnabled(True)
        self.list_dept.setDragDropOverwriteMode(False)
        self.list_dept.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.list_dept.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.list_dept.setObjectName("list_dept")
        self.lineEdit = CustomLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setMaxLength(10)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 744, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuSet_opacity = QtWidgets.QMenu(self.menuSettings)
        self.menuSet_opacity.setObjectName("menuSet_opacity")
        MainWindow.setMenuBar(self.menuBar)
        self.actionStay_on_top = QtWidgets.QAction(MainWindow)
        self.actionStay_on_top.setCheckable(True)
        self.actionStay_on_top.setObjectName("actionStay_on_top")
        self.actionStatistics = QtWidgets.QAction(MainWindow)
        self.actionStatistics.setObjectName("actionStatistics")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpac_Incr = QtWidgets.QAction(MainWindow)
        self.actionOpac_Incr.setObjectName("actionOpac_Incr")
        self.actionOpac_Decr = QtWidgets.QAction(MainWindow)
        self.actionOpac_Decr.setObjectName("actionOpac_Decr")
        self.actionOpac_Rest = QtWidgets.QAction(MainWindow)
        self.actionOpac_Rest.setObjectName("actionOpac_Rest")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionOpac_Curr = QtWidgets.QAction(MainWindow)
        self.actionOpac_Curr.setEnabled(False)
        self.actionOpac_Curr.setObjectName("actionOpac_Curr")
        self.menuSet_opacity.addAction(self.actionOpac_Curr)
        self.menuSet_opacity.addSeparator()
        self.menuSet_opacity.addAction(self.actionOpac_Incr)
        self.menuSet_opacity.addAction(self.actionOpac_Decr)
        self.menuSet_opacity.addAction(self.actionOpac_Rest)
        self.menuSettings.addAction(self.menuSet_opacity.menuAction())
        self.menuSettings.addAction(self.actionStay_on_top)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionStatistics)
        self.menuSettings.addAction(self.actionAbout)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionReset)
        self.menuSettings.addAction(self.actionExit)
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.btn_add.clicked.connect(MainWindow.addFlight)
        self.btn_reset.clicked.connect(MainWindow.resetLists)
        self.lineEdit.returnPressed.connect(self.btn_add.click)
        self.list_push.itemDoubleClicked['QListWidgetItem*'].connect(MainWindow.setStatusClr)
        self.list_dept.itemDoubleClicked['QListWidgetItem*'].connect(MainWindow.setStatusDep)
        self.list_pend.itemDoubleClicked['QListWidgetItem*'].connect(MainWindow.setStatusClr)
        self.menuBar.triggered['QAction*'].connect(MainWindow.clickMenu)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.btn_add)
        MainWindow.setTabOrder(self.btn_add, self.list_pend)
        MainWindow.setTabOrder(self.list_pend, self.list_push)
        MainWindow.setTabOrder(self.list_push, self.list_dept)
        MainWindow.setTabOrder(self.list_dept, self.btn_reset)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Flight Strip Manager"))
        self.btn_add.setText(_translate("MainWindow", "ADD"))
        self.btn_reset.setText(_translate("MainWindow", "RESET"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Callsign"))
        self.menuSettings.setTitle(_translate("MainWindow", "Menu"))
        self.menuSet_opacity.setTitle(_translate("MainWindow", "Set opacity"))
        self.actionStay_on_top.setText(_translate("MainWindow", "Stay on top"))
        self.actionStay_on_top.setShortcut(_translate("MainWindow", "Alt+Return"))
        self.actionStatistics.setText(_translate("MainWindow", "Statistics"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpac_Incr.setText(_translate("MainWindow", "Increase"))
        self.actionOpac_Incr.setShortcut(_translate("MainWindow", "Alt+="))
        self.actionOpac_Decr.setText(_translate("MainWindow", "Decrease"))
        self.actionOpac_Decr.setShortcut(_translate("MainWindow", "Alt+-"))
        self.actionOpac_Rest.setText(_translate("MainWindow", "Reset"))
        self.actionOpac_Rest.setShortcut(_translate("MainWindow", "Alt+Backspace"))
        self.actionReset.setText(_translate("MainWindow", "Reset lists"))
        self.actionOpac_Curr.setText(_translate("MainWindow", "Current:"))
